### ISSUE TITLE
couldn't find boost

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [gsneha26/SegAlign#44]
Hello there,
I have been trying to install GPU version of cactus on linux centos7 cluster. I followed the installation guidelines on "installUbuntu.sh" under scripts. however I had an error while running cmake.
I am not sure how to install boost so I installed using Conda 

module load 7/compiler/cuda/10.0
conda activate segAlign
conda install -c statiskit libboost-dev
conda install -c intel tbb

I also attached the file: SegAlign/build/CMakeFiles/CMakeError.log.

Any insights? thanks a lot, really appreciate your help!
Zhenzhen 

[CMakeError.log](https://github.com/gsneha26/SegAlign/files/5773893/CMakeError.log)

-- The CXX compiler identification is GNU 4.8.5
-- The CUDA compiler identification is NVIDIA 10.0.130
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /public/software/compiler/cuda/7/cuda-10.0/bin/nvcc
-- Check for working CUDA compiler: /public/software/compiler/cuda/7/cuda-10.0/bin/nvcc - works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /public/software/compiler/cuda/7/cuda-10.0 (found suitable version "10.0", minimum required is "9.0")
-- Intel TBB can not be built: Makefile or src directory was not found in /public/home/yangzhzh/tools_zz/SegAlign/build/../tbb2019_20191006oss
CMake Warning (dev) at CMakeLists.txt:17 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable TBB_ROOT is set to:

    /public/home/yangzhzh/tools_zz/SegAlign/build/../tbb2019_20191006oss

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
CMake Error at /public/software/apps/cmake/3.17.2/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options)
Call Stack (most recent call first):
  /public/software/apps/cmake/3.17.2/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /public/software/apps/cmake/3.17.2/share/cmake-3.17/Modules/FindBoost.cmake:2162 (find_package_handle_standard_args)
  CMakeLists.txt:23 (find_package)

-- Configuring incomplete, errors occurred!
See also "/public/home/yangzhzh/tools_zz/SegAlign/build/CMakeFiles/CMakeOutput.log".
See also "/public/home/yangzhzh/tools_zz/SegAlign/build/CMakeFiles/CMakeError.log".

**Comment by gsneha26** [comment]
you can install boost using `sudo yum -y install boost-devel`

**Comment by zhenzhenyang-psu** [comment]
thanks very much.
I have re-installed the cuda10.2 driver.
However, because I don't have sudo-root privileges to use sudo yum install, i used conda to install boost.
conda install -c statiskit libboost-dev

However, when I did "cmake", the following message occurred:
cmake -DCMAKE_BUILD_TYPE=Release -DTBB_ROOT=${PWD}/../tbb2019_20191006oss -DCMAKE_PREFIX_PATH=${PWD}/../tbb2019_20191006oss/cmake ..
-- The CXX compiler identification is GNU 4.8.5
-- The CUDA compiler identification is NVIDIA 10.2.89c
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /public/software/compiler/cuda/7/cuda-10.2/bin/nvcc
-- Check for working CUDA compiler: /public/software/compiler/cuda/7/cuda-10.2/bin/nvcc - works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /public/software/compiler/cuda/7/cuda-10.2 (found suitable version "10.2", minimum required is "9.0")
-- Intel TBB can not be built: Makefile or src directory was not found in /public/home/yangzhzh/tools_zz/SegAlign/build/../tbb2019_20191006oss
CMake Warning (dev) at CMakeLists.txt:17 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable TBB_ROOT is set to:

    /public/home/yangzhzh/tools_zz/SegAlign/build/../tbb2019_20191006oss

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found Boost: /public/software/apps/boost/1.64.0/include (found version "1.64.0") found components: program_options
-- Configuring done
-- Generating done
-- Build files have been written to: /public/home/yangzhzh/tools_zz/SegAlign/build


Do you think this step is successful?
Then I did make -j $(nproc)
Scanning dependencies of target segalign
Scanning dependencies of target segalign_repeat_masker
[ 35%] Building CXX object CMakeFiles/segalign.dir/common/DRAM.cpp.o
[ 35%] Building CUDA object CMakeFiles/segalign_repeat_masker.dir/common/seed_filter_interface.cu.o
[ 40%] Building CXX object CMakeFiles/segalign_repeat_masker.dir/common/ntcoding.cpp.o
[ 40%] Building CXX object CMakeFiles/segalign_repeat_masker.dir/common/DRAM.cpp.o
[ 40%] Building CXX object CMakeFiles/segalign.dir/common/ntcoding.cpp.o
[ 40%] Building CUDA object CMakeFiles/segalign.dir/common/seed_filter_interface.cu.o
[ 40%] Building CUDA object CMakeFiles/segalign.dir/common/seed_pos_table.cu.o
[ 40%] Building CUDA object CMakeFiles/segalign_repeat_masker.dir/common/seed_pos_table.cu.o
[ 45%] Building CUDA object CMakeFiles/segalign.dir/src/seed_filter.cu.o
[ 60%] Building CXX object CMakeFiles/segalign.dir/src/seeder.cpp.o
[ 60%] Building CUDA object CMakeFiles/segalign_repeat_masker.dir/repeat_masker_src/seed_filter.cu.o
[ 60%] Building CXX object CMakeFiles/segalign.dir/src/segment_printer.cpp.o
[ 65%] Building CXX object CMakeFiles/segalign_repeat_masker.dir/repeat_masker_src/seeder.cpp.o
[ 70%] Building CXX object CMakeFiles/segalign_repeat_masker.dir/repeat_masker_src/segment_printer.cpp.o
[ 80%] Building CXX object CMakeFiles/segalign_repeat_masker.dir/repeat_masker_src/main.cpp.o
[ 80%] Building CXX object CMakeFiles/segalign.dir/src/main.cpp.o
[ 85%] Linking CUDA device code CMakeFiles/segalign.dir/cmake_device_link.o
[ 90%] Linking CXX executable segalign
/usr/bin/ld: cannot find -lboost_program_options
collect2: error: ld returned 1 exit status
make[2]: *** [segalign] Error 1
make[1]: *** [CMakeFiles/segalign.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 95%] Linking CUDA device code CMakeFiles/segalign_repeat_masker.dir/cmake_device_link.o
[100%] Linking CXX executable segalign_repeat_masker
/usr/bin/ld: cannot find -lboost_program_options
collect2: error: ld returned 1 exit status
make[2]: *** [segalign_repeat_masker] Error 1
make[1]: *** [CMakeFiles/segalign_repeat_masker.dir/all] Error 2
make: *** [all] Error 2

It seems that boost is still a source of the problem.
Why conda installing boost won't solve the problem? Could any settings be configured if using conda installed boost?
Also does this suggest additional problems in addition to boost?
I will ask our HPC folks to install boost and see if this problem remains.
thanks very much for your help!
zhenzhen
________________________________

**Comment by gsneha26** [comment]
Please pull the latest commit, the tbb issue has been resolved in that.

**Comment by zhenzhenyang-psu** [comment]
that's great! I will try it, thanks!

________________________________

**Comment by zhenzhenyang-psu** [comment]
Hello,
I am sorry that I still have the following error during compilation, see below:

module load 7/compiler/cuda/10.2
export PATH=/public/software/compiler/cuda/7/cuda-10.2/bin/:$PATH

module load apps/boost/1.64.0 

module load 7/apps/cmake_3.17.2
mkdir -p build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DTBB_ROOT=${PWD}/../oneTBB-2019_U9 -DCMAKE_PREFIX_PATH=${PWD}/../oneTBB-2019_U9/cmake ..
-- The CXX compiler identification is GNU 4.8.5
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /public/software/compiler/cuda/7/cuda-10.2/bin/nvcc
-- Check for working CUDA compiler: /public/software/compiler/cuda/7/cuda-10.2/bin/nvcc - works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /public/software/compiler/cuda/7/cuda-10.2 (found suitable version "10.2", minimum required is "9.0") 
-- Building Intel TBB: /usr/local/bin/make -j8 tbb_build_prefix=tbb_cmake_build_subdir tbb_build_dir=/public/home/yangzhzh/tools_zz/SegAlign/build/tbb_cmake_build compiler=gcc tbb_cpf=1
CMake Warning (dev) at CMakeLists.txt:17 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable TBB_ROOT is set to:

    /public/home/yangzhzh/tools_zz/SegAlign/build/../oneTBB-2019_U9

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found Boost: /public/software/apps/boost/1.64.0/include (found version "1.64.0") found components: program_options 
-- Configuring done
-- Generating done
-- Build files have been written to: /public/home/yangzhzh/tools_zz/SegAlign/build

make -j $(nproc)
Scanning dependencies of target segalign
Scanning dependencies of target segalign_repeat_masker

[ 25%] Building CUDA object CMakeFiles/segalign.dir/common/seed_pos_table.cu.o
[ 30%] Building CXX object CMakeFiles/segalign.dir/src/seeder.cpp.o
[ 30%] Building CXX object CMakeFiles/segalign.dir/common/ntcoding.cpp.o
[ 35%] Building CXX object CMakeFiles/segalign.dir/src/segment_printer.cpp.o
[ 40%] Building CUDA object CMakeFiles/segalign.dir/common/seed_filter_interface.cu.o
[ 35%] Building CXX object CMakeFiles/segalign.dir/common/DRAM.cpp.o
[ 40%] Building CUDA object CMakeFiles/segalign.dir/src/seed_filter.cu.o
[ 40%] Building CXX object CMakeFiles/segalign_repeat_masker.dir/common/DRAM.cpp.o
[ 45%] Building CXX object CMakeFiles/segalign.dir/src/main.cpp.o
[ 55%] Building CXX object CMakeFiles/segalign_repeat_masker.dir/common/ntcoding.cpp.o
[ 55%] Building CUDA object CMakeFiles/segalign_repeat_masker.dir/common/seed_filter_interface.cu.o
[ 60%] Building CUDA object CMakeFiles/segalign_repeat_masker.dir/common/seed_pos_table.cu.o
[ 65%] Building CUDA object CMakeFiles/segalign_repeat_masker.dir/repeat_masker_src/seed_filter.cu.o
[ 70%] Building CXX object CMakeFiles/segalign_repeat_masker.dir/repeat_masker_src/seeder.cpp.o
[ 75%] Building CXX object CMakeFiles/segalign_repeat_masker.dir/repeat_masker_src/segment_printer.cpp.o
[ 80%] Building CXX object CMakeFiles/segalign_repeat_masker.dir/repeat_masker_src/main.cpp.o
[ 85%] Linking CUDA device code CMakeFiles/segalign.dir/cmake_device_link.o
[ 90%] Linking CUDA device code CMakeFiles/segalign_repeat_masker.dir/cmake_device_link.o
[ 95%] Linking CXX executable segalign
[100%] Linking CXX executable segalign_repeat_masker
/usr/bin/ld/: usrcannot/ binfind/ld: cannot find  --lboost_program_optionslboost_program_options

collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make[2]: *** [segalign] Error 1
make[2]: *** [segalign_repeat_masker] Error 1
make[1]: *** [CMakeFiles/segalign.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/segalign_repeat_masker.dir/all] Error 2
make: *** [all] Error 2

any thoughts?
thanks,
Zhenzhen

**Comment by gsneha26** [comment]
It seems to be a boost linking issue, maybe you could try local installation of boost from `https://www.boost.org`

**Comment by gsneha26** [comment]
@zhenzhenyang-psu you might want to use Docker for this one - I am developing this further, you might want to look at the docker branch.
